function yoncaerp(){var cb='',_=' top: -1000px;',zb='" for "gwt:onLoadErrorFn"',xb='" for "gwt:onPropertyErrorFn"',ib='");',Ab='#',Pc='.cache.js',Cb='/',Ib='//',qc='2E9320535D1DCEC78ACA6FBD9237DBE4',uc='74B8119D0BD4451EEDECE578CD6C14DB',vc='93552D451799C8698CC929A43F31C109',wc='9EF794154712DCFB1A64180F4CCD153C',Oc=':',rc=':1',xc=':10',yc=':11',zc=':12',Ac=':13',Bc=':14',Cc=':15',Dc=':16',Ec=':17',Fc=':18',Gc=':19',sc=':2',tc=':3',Hc=':4',Ic=':5',Jc=':6',Kc=':7',Lc=':8',Mc=':9',rb='::',Xc=':moduleBase',bb='<!doctype html>',db='<html><head><\/head><body><\/body><\/html>',ub='=',Bb='?',wb='Bad handler "',ab='CSS1Compat',gb='Chrome',Nc='D1852BD27B0E06569CB4C60369CA344E',fb='DOMContentLoaded',W='DUMMY',Wc='Ignoring non-whitelisted Dev Mode URL: ',Vc='__gwtDevModeHook:yoncaerp',Uc='_gwt_dummy_',cc='adobeair',dc='air',Hb='base',Fb='baseUrl',R='begin',X='body',Q='bootstrap',Kb='chrome',Eb='clear.cache.gif',tb='content',Rc='end',hb='eval("',Tc='file:',$b='gecko',ac='gecko1_8',bc='gecko1_9',S='gwt.codesvr.yoncaerp=',T='gwt.codesvr=',yb='gwt:onLoadErrorFn',vb='gwt:onPropertyErrorFn',sb='gwt:property',Jb='gxt.user.agent',nb='head',Sc='http:',Nb='ie10',Tb='ie6',Rb='ie7',Pb='ie8',Ob='ie9',Y='iframe',Db='img',kb='javascript',Z='javascript:""',lc='linux',Qc='loadExternalRefs',kc='mac',jc='mac os x',ic='macintosh',ob='meta',mb='moduleRequested',lb='moduleStartup',Mb='msie',Sb='msie 6',Qb='msie 7',pb='name',Lb='opera',$='position:absolute; width:0; height:0; border:none; left: -1000px;',_b='rv:1.8',Ub='safari',Wb='safari3',Yb='safari4',Zb='safari5',jb='script',oc='selectingPermutation',V='startup',eb='undefined',gc='unknown',ec='user.agent',hc='user.agent.os',Vb='version/3',Xb='version/4',fc='webkit',nc='win32',mc='windows',U='yoncaerp',pc='yoncaerp.devmode.js',Gb='yoncaerp.nocache.js',qb='yoncaerp::';var o=window;var p=document;r(Q,R);function q(){var a=o.location.search;return a.indexOf(S)!=-1||a.indexOf(T)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:U,sessionId:o.__gwtStatsSessionId,subSystem:V,evtGroup:a,millis:(new Date).getTime(),type:b})}}
yoncaerp.__sendStats=r;yoncaerp.__moduleName=U;yoncaerp.__errFn=null;yoncaerp.__moduleBase=W;yoncaerp.__softPermutationId=0;yoncaerp.__computePropValue=null;yoncaerp.__getPropMap=null;yoncaerp.__gwtInstallCode=function(){};yoncaerp.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[U]={moduleName:U};var v;function w(){B();return v}
function A(){B();return v.getElementsByTagName(X)[0]}
function B(){if(v){return}var a=p.createElement(Y);a.src=Z;a.id=U;a.style.cssText=$+_;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();var b=document.compatMode==ab?bb:cb;v.write(b+db);v.close()}
function C(k){function l(a){function b(){if(typeof p.readyState==eb){return typeof p.body!=eb&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(fb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(fb,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=A();var f=w();var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(hb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(ib));g=f.createElement(jb);g.language=kb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(jb);g.language=kb;g.text=c[i];e.appendChild(g);d(e,g)}}}
yoncaerp.onScriptDownloaded=function(a){l(function(){m(a)})};r(lb,mb);var n=p.createElement(jb);n.src=k;p.getElementsByTagName(nb)[0].appendChild(n)}
yoncaerp.__startLoadingFragment=function(a){return G(a)};yoncaerp.__installRunAsyncCode=function(a){var b=A();var c=w().createElement(jb);c.language=kb;c.text=a;b.appendChild(c);b.removeChild(c)};function D(){var c={};var d;var e;var f=p.getElementsByTagName(ob);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(pb),k;if(j){j=j.replace(qb,cb);if(j.indexOf(rb)>=0){continue}if(j==sb){k=i.getAttribute(tb);if(k){var l,m=k.indexOf(ub);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=cb}c[j]=l}}else if(j==vb){k=i.getAttribute(tb);if(k){try{d=eval(k)}catch(a){alert(wb+k+xb)}}}else if(j==yb){k=i.getAttribute(tb);if(k){try{e=eval(k)}catch(a){alert(wb+k+zb)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;yoncaerp.__errFn=e}
function F(){function e(a){var b=a.lastIndexOf(Ab);if(b==-1){b=a.length}var c=a.indexOf(Bb);if(c==-1){c=a.length}var d=a.lastIndexOf(Cb,Math.min(c,b));return d>=0?a.substring(0,d+1):cb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Db);b.src=a+Eb;a=e(b.src)}return a}
function g(){var a=t(Fb);if(a!=null){return a}return cb}
function h(){var a=p.getElementsByTagName(jb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Gb)!=-1){return e(a[b].src)}}return cb}
function i(){var a=p.getElementsByTagName(Hb);if(a.length>0){return a[a.length-1].href}return cb}
function j(){var a=p.location;return a.href==a.protocol+Ib+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==cb){k=h()}if(k==cb){k=i()}if(k==cb&&j()){k=e(p.location.href)}k=f(k);return k}
function G(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return yoncaerp.__moduleBase+a}
function H(){var f=[];var g=0;function h(a,b){var c=f;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[Jb]=function(){var a=navigator.userAgent.toLowerCase();if(a.indexOf(Kb)!=-1)return Kb;if(a.indexOf(Lb)!=-1)return Lb;if(a.indexOf(Mb)!=-1){if(p.documentMode>=10)return Nb;if(p.documentMode>=9)return Ob;if(p.documentMode>=8)return Pb;if(a.indexOf(Qb)!=-1)return Rb;if(a.indexOf(Sb)!=-1)return Tb;return Nb}if(a.indexOf(Ub)!=-1){if(a.indexOf(Vb)!=-1)return Wb;if(a.indexOf(Xb)!=-1)return Yb;return Zb}if(a.indexOf($b)!=-1){if(a.indexOf(_b)!=-1)return ac;return bc}if(a.indexOf(cc)!=-1)return dc;return null};i[Jb]={air:0,chrome:1,gecko1_8:2,gecko1_9:3,ie10:4,ie8:5,ie9:6,safari3:7,safari4:8,safari5:9};j[ec]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(fc)!=-1}())return Ub;if(function(){return b.indexOf(Mb)!=-1&&p.documentMode>=10}())return Nb;if(function(){return b.indexOf(Mb)!=-1&&p.documentMode>=9}())return Ob;if(function(){return b.indexOf(Mb)!=-1&&p.documentMode>=8}())return Pb;if(function(){return b.indexOf($b)!=-1}())return ac;return gc};i[ec]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};j[hc]=function(){var a=o.navigator.userAgent.toLowerCase();if(a.indexOf(ic)!=-1||a.indexOf(jc)!=-1){return kc}if(a.indexOf(lc)!=-1){return lc}if(a.indexOf(mc)!=-1||a.indexOf(nc)!=-1){return mc}return gc};i[hc]={linux:0,mac:1,unknown:2,windows:3};s=function(a,b){return b in i[a]};yoncaerp.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};yoncaerp.__computePropValue=k;o.__gwt_activeModules[U].bindings=yoncaerp.__getPropMap;r(Q,oc);if(q()){return G(pc)}var l;try{h([Pb,Pb,lc],qc);h([Pb,Pb,kc],qc+rc);h([Pb,Pb,gc],qc+sc);h([Pb,Pb,mc],qc+tc);h([Nb,Nb,lc],uc);h([Nb,Nb,kc],uc+rc);h([Nb,Nb,gc],uc+sc);h([Nb,Nb,mc],uc+tc);h([Ob,Ob,lc],vc);h([Ob,Ob,kc],vc+rc);h([Ob,Ob,gc],vc+sc);h([Ob,Ob,mc],vc+tc);h([dc,Ub,lc],wc);h([dc,Ub,kc],wc+rc);h([Wb,Ub,gc],wc+xc);h([Wb,Ub,mc],wc+yc);h([Yb,Ub,lc],wc+zc);h([Yb,Ub,kc],wc+Ac);h([Yb,Ub,gc],wc+Bc);h([Yb,Ub,mc],wc+Cc);h([Zb,Ub,lc],wc+Dc);h([Zb,Ub,kc],wc+Ec);h([Zb,Ub,gc],wc+Fc);h([Zb,Ub,mc],wc+Gc);h([dc,Ub,gc],wc+sc);h([dc,Ub,mc],wc+tc);h([Kb,Ub,lc],wc+Hc);h([Kb,Ub,kc],wc+Ic);h([Kb,Ub,gc],wc+Jc);h([Kb,Ub,mc],wc+Kc);h([Wb,Ub,lc],wc+Lc);h([Wb,Ub,kc],wc+Mc);h([ac,ac,lc],Nc);h([ac,ac,kc],Nc+rc);h([ac,ac,gc],Nc+sc);h([ac,ac,mc],Nc+tc);h([bc,ac,lc],Nc+Hc);h([bc,ac,kc],Nc+Ic);h([bc,ac,gc],Nc+Jc);h([bc,ac,mc],Nc+Kc);l=f[k(Jb)][k(ec)][k(hc)];var m=l.indexOf(Oc);if(m!=-1){g=parseInt(l.substring(m+1),10);l=l.substring(0,m)}}catch(a){}yoncaerp.__softPermutationId=g;return G(l+Pc)}
function I(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(Qc,R);r(Qc,Rc)}
D();yoncaerp.__moduleBase=F();u[U].moduleBase=yoncaerp.__moduleBase;var J=H();if(o){var K=!!(o.location.protocol==Sc||o.location.protocol==Tc);o.__gwt_activeModules[U].canRedirect=K;function L(){var b=Uc;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(K&&L()){var M=Vc;var N=o.sessionStorage[M];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(N)){if(N&&(window.console&&console.log)){console.log(Wc+N)}N=cb}if(N&&!o[M]){o[M]=true;o[M+Xc]=F();var O=p.createElement(jb);O.src=N;var P=p.getElementsByTagName(nb)[0];P.insertBefore(O,P.firstElementChild||P.children[0]);return false}}}I();r(Q,Rc);C(J);return true}
yoncaerp.succeeded=yoncaerp();